import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased font-lato"
      >
        <header className="flex items-center justify-center p-6 border-b border-tertinary">
          <Link href='/' className="font-boldonse tracking-wide text-secondary text-center">RecipeFinderApp</Link>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
